workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic Admin
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.queue.loansimulator
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          set -ex
          echo "Setting up code signing..."
          keychain initialize
          app-store-connect fetch-signing-files com.queue.loansimulator \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          set -ex
          flutter pub get
      
      - name: Build iOS
        script: |
          set -ex
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - 4817maymay@gmail.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true