workflows:
  ios-workflow:
    name: iOS Workflow - Debug
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic Admin
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug - Check directory structure
        script: |
          #!/bin/sh
          set -x
          pwd
          ls -la
          echo "=== Checking pubspec.yaml ==="
          if [ -f "pubspec.yaml" ]; then
            echo "✅ pubspec.yaml found"
            cat pubspec.yaml | head -30
          else
            echo "❌ pubspec.yaml NOT found"
            find . -name "pubspec.yaml"
          fi
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get